const { neon } = require("@neondatabase/serverless");
const { getAdminLocketUids, getAdminLocketEmails } = require("./locketAdminVerifier");
const { getRequestContext } = require("./userActivityContext");

const ONLINE_WINDOW_SECONDS = 150;
let schemaPromise = null;

function getDatabaseUrl() {
  return [process.env.DATABASE_URL, process.env.NEON_DATABASE_URL]
    .find((value) => typeof value === "string" && value.trim())
    ?.trim() || null;
}

function getSql() {
  const databaseUrl = getDatabaseUrl();
  return databaseUrl ? neon(databaseUrl) : null;
}

function hasActivityDatabase() {
  return Boolean(getDatabaseUrl());
}

async function ensureUserActivitySchema() {
  const sql = getSql();
  if (!sql) {
    const error = new Error("User activity database is not configured");
    error.code = "DATABASE_NOT_CONFIGURED";
    throw error;
  }
  if (schemaPromise) return schemaPromise;

  schemaPromise = (async () => {
    await sql`CREATE TABLE IF NOT EXISTS web_users (
      uid TEXT PRIMARY KEY,
      internal_id UUID NOT NULL DEFAULT gen_random_uuid(),
      email TEXT,
      username TEXT,
      display_name TEXT,
      profile_picture TEXT,
      provider TEXT,
      disabled BOOLEAN NOT NULL DEFAULT FALSE,
      last_sign_in_at TIMESTAMPTZ,
      ip_address TEXT,
      browser TEXT,
      os TEXT,
      auth_provider TEXT NOT NULL DEFAULT 'locket-firebase',
      login_method TEXT NOT NULL DEFAULT 'unknown',
      account_status TEXT NOT NULL DEFAULT 'active',
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      last_login_at TIMESTAMPTZ,
      last_seen_at TIMESTAMPTZ,
      last_logout_at TIMESTAMPTZ,
      current_web_source TEXT,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )`;
    await sql`ALTER TABLE web_users ADD COLUMN IF NOT EXISTS internal_id UUID DEFAULT gen_random_uuid()`;
    await sql`ALTER TABLE web_users ADD COLUMN IF NOT EXISTS provider TEXT`;
    await sql`ALTER TABLE web_users ADD COLUMN IF NOT EXISTS disabled BOOLEAN DEFAULT FALSE`;
    await sql`ALTER TABLE web_users ADD COLUMN IF NOT EXISTS last_sign_in_at TIMESTAMPTZ`;
    await sql`ALTER TABLE web_users ADD COLUMN IF NOT EXISTS ip_address TEXT`;
    await sql`ALTER TABLE web_users ADD COLUMN IF NOT EXISTS browser TEXT`;
    await sql`ALTER TABLE web_users ADD COLUMN IF NOT EXISTS os TEXT`;
    await sql`ALTER TABLE web_users ADD COLUMN IF NOT EXISTS auth_provider TEXT DEFAULT 'locket-firebase'`;
    await sql`ALTER TABLE web_users ADD COLUMN IF NOT EXISTS login_method TEXT DEFAULT 'unknown'`;
    await sql`ALTER TABLE web_users ADD COLUMN IF NOT EXISTS account_status TEXT DEFAULT 'active'`;
    await sql`ALTER TABLE web_users ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMPTZ`;
    await sql`ALTER TABLE web_users ADD COLUMN IF NOT EXISTS last_seen_at TIMESTAMPTZ`;
    await sql`ALTER TABLE web_users ADD COLUMN IF NOT EXISTS last_logout_at TIMESTAMPTZ`;
    await sql`ALTER TABLE web_users ADD COLUMN IF NOT EXISTS current_web_source TEXT`;
    await sql`ALTER TABLE web_users ADD COLUMN IF NOT EXISTS gps_coordinates TEXT`;
    await sql`ALTER TABLE web_users ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW()`;
    await sql`ALTER TABLE web_users ADD COLUMN IF NOT EXISTS two_factor_secret TEXT DEFAULT NULL`;
    await sql`ALTER TABLE web_users ADD COLUMN IF NOT EXISTS is_two_factor_enabled BOOLEAN DEFAULT FALSE`;
    await sql`UPDATE web_users SET
      internal_id = COALESCE(internal_id, gen_random_uuid()),
      auth_provider = COALESCE(auth_provider, provider, 'locket-firebase'),
      login_method = COALESCE(login_method, 'unknown'),
      account_status = CASE WHEN COALESCE(disabled, FALSE) THEN 'locked' ELSE COALESCE(account_status, 'active') END,
      last_login_at = COALESCE(last_login_at, last_sign_in_at),
      last_seen_at = COALESCE(last_seen_at, last_sign_in_at),
      updated_at = COALESCE(updated_at, NOW())`;
    await sql`CREATE UNIQUE INDEX IF NOT EXISTS web_users_internal_id_idx ON web_users (internal_id)`;
    await sql`CREATE INDEX IF NOT EXISTS web_users_last_seen_idx ON web_users (last_seen_at DESC)`;

    await sql`CREATE TABLE IF NOT EXISTS user_sessions (
      session_id UUID PRIMARY KEY,
      user_uid TEXT NOT NULL REFERENCES web_users(uid) ON DELETE CASCADE,
      web_source TEXT NOT NULL DEFAULT 'unknown',
      started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      ended_at TIMESTAMPTZ,
      status TEXT NOT NULL DEFAULT 'active'
    )`;
    await sql`CREATE INDEX IF NOT EXISTS user_sessions_user_idx ON user_sessions (user_uid, last_seen_at DESC)`;
    await sql`CREATE INDEX IF NOT EXISTS user_sessions_presence_idx ON user_sessions (status, last_seen_at DESC)`;

    await sql`CREATE TABLE IF NOT EXISTS login_history (
      event_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
      uid TEXT NOT NULL,
      session_id UUID,
      ip_address TEXT,
      country TEXT,
      region TEXT,
      city TEXT,
      browser TEXT,
      browser_version TEXT,
      os TEXT,
      device TEXT,
      login_method TEXT,
      web_source TEXT,
      web_version TEXT,
      build_id TEXT,
      commit_hash TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      ended_at TIMESTAMPTZ
    )`;
    await sql`ALTER TABLE login_history ADD COLUMN IF NOT EXISTS event_id BIGINT GENERATED BY DEFAULT AS IDENTITY`;
    await sql`ALTER TABLE login_history ADD COLUMN IF NOT EXISTS session_id UUID`;
    await sql`ALTER TABLE login_history ADD COLUMN IF NOT EXISTS region TEXT`;
    await sql`ALTER TABLE login_history ADD COLUMN IF NOT EXISTS browser_version TEXT`;
    await sql`ALTER TABLE login_history ADD COLUMN IF NOT EXISTS web_source TEXT`;
    await sql`ALTER TABLE login_history ADD COLUMN IF NOT EXISTS web_version TEXT`;
    await sql`ALTER TABLE login_history ADD COLUMN IF NOT EXISTS build_id TEXT`;
    await sql`ALTER TABLE login_history ADD COLUMN IF NOT EXISTS commit_hash TEXT`;
    await sql`ALTER TABLE login_history ADD COLUMN IF NOT EXISTS gps_coordinates TEXT`;
    await sql`ALTER TABLE login_history ADD COLUMN IF NOT EXISTS last_seen_at TIMESTAMPTZ DEFAULT NOW()`;
    await sql`ALTER TABLE login_history ADD COLUMN IF NOT EXISTS ended_at TIMESTAMPTZ`;
    await sql`CREATE UNIQUE INDEX IF NOT EXISTS login_history_session_idx ON login_history (session_id) WHERE session_id IS NOT NULL`;
    await sql`CREATE INDEX IF NOT EXISTS login_history_user_idx ON login_history (uid, created_at DESC)`;

    await sql`CREATE TABLE IF NOT EXISTS admin_audit_log (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      admin_uid TEXT NOT NULL,
      action TEXT NOT NULL,
      target_uid TEXT,
      details TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )`;
    await sql`ALTER TABLE admin_audit_log ADD COLUMN IF NOT EXISTS role TEXT`;
    await sql`ALTER TABLE admin_audit_log ADD COLUMN IF NOT EXISTS ip_address TEXT`;
    await sql`ALTER TABLE admin_audit_log ADD COLUMN IF NOT EXISTS web_source TEXT`;
    await sql`ALTER TABLE admin_audit_log ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'success'`;
    await sql`CREATE INDEX IF NOT EXISTS admin_audit_log_created_idx ON admin_audit_log (created_at DESC)`;

    await sql`CREATE TABLE IF NOT EXISTS admin_roles (
      uid TEXT PRIMARY KEY,
      role TEXT NOT NULL DEFAULT 'user',
      assigned_by TEXT,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )`;
    await sql`ALTER TABLE admin_roles ADD COLUMN IF NOT EXISTS pin_hash TEXT`;

    await sql`CREATE TABLE IF NOT EXISTS admin_sessions (
      token_hash TEXT PRIMARY KEY,
      uid TEXT NOT NULL,
      expires_at TIMESTAMPTZ NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )`;
    await sql`CREATE INDEX IF NOT EXISTS admin_sessions_uid_idx ON admin_sessions (uid, expires_at DESC)`;

    await sql`CREATE TABLE IF NOT EXISTS reported_content (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      content_id TEXT NOT NULL,
      content_type TEXT NOT NULL DEFAULT 'post',
      author_uid TEXT,
      reporter_uid TEXT,
      reason TEXT,
      status TEXT NOT NULL DEFAULT 'pending',
      action_taken TEXT,
      resolved_by TEXT,
      resolved_at TIMESTAMPTZ,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )`;

    await sql`CREATE TABLE IF NOT EXISTS global_broadcasts (
      id INT PRIMARY KEY DEFAULT 1,
      message TEXT NOT NULL,
      level TEXT NOT NULL DEFAULT 'info',
      active BOOLEAN NOT NULL DEFAULT TRUE,
      target_user TEXT NOT NULL DEFAULT 'ALL',
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )`;
    try {
      await sql`ALTER TABLE global_broadcasts ADD COLUMN IF NOT EXISTS target_user TEXT NOT NULL DEFAULT 'ALL'`;
    } catch (e) {
      /* ignore if exists */
    }

    
    await sql`CREATE TABLE IF NOT EXISTS web_security_whitelist (
      identifier TEXT PRIMARY KEY,
      type TEXT NOT NULL,
      added_by TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )`;

    await sql`CREATE TABLE IF NOT EXISTS ip_blacklist (
      ip_address TEXT PRIMARY KEY,
      reason TEXT,
      blocked_by TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )`;

    await sql`CREATE TABLE IF NOT EXISTS celebrity_profiles (
      id SERIAL PRIMARY KEY,
      uid TEXT UNIQUE NOT NULL,
      username TEXT,
      display_name TEXT,
      avatar_url TEXT,
      locket_url TEXT,
      country_code TEXT DEFAULT 'VN',
      enabled BOOLEAN DEFAULT TRUE,
      sort_order INT DEFAULT 0,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )`;
    await sql`ALTER TABLE celebrity_profiles
      ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()`;

    await sql`CREATE TABLE IF NOT EXISTS web_user_actions (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      uid TEXT NOT NULL,
      email TEXT,
      display_name TEXT,
      profile_picture TEXT,
      action_type TEXT NOT NULL,
      action_title TEXT NOT NULL,
      details TEXT,
      ip_address TEXT,
      device TEXT,
      browser TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )`;
    await sql`CREATE INDEX IF NOT EXISTS web_user_actions_created_idx ON web_user_actions (created_at DESC)`;
    await sql`CREATE INDEX IF NOT EXISTS web_user_actions_uid_idx ON web_user_actions (uid, created_at DESC)`;

    await sql`CREATE TABLE IF NOT EXISTS web_security_threats (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      threat_type TEXT NOT NULL,
      severity TEXT NOT NULL,
      target_endpoint TEXT,
      attacker_ip TEXT,
      user_uid TEXT,
      user_email TEXT,
      user_agent TEXT,
      details TEXT,
      payload_sample TEXT,
      status TEXT NOT NULL DEFAULT 'BLOCKED',
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )`;
    await sql`CREATE INDEX IF NOT EXISTS web_security_threats_created_idx ON web_security_threats (created_at DESC)`;
    await sql`CREATE INDEX IF NOT EXISTS web_security_threats_severity_idx ON web_security_threats (severity)`;

    await sql`
      INSERT INTO web_users (uid, auth_provider, account_status, created_at, last_seen_at, current_web_source, updated_at)
      SELECT uid, 'locket-firebase', 'active', COALESCE(MIN(created_at), NOW()), COALESCE(MAX(created_at), NOW()), 'web-locket', NOW()
      FROM login_history
      GROUP BY uid
      ON CONFLICT (uid) DO NOTHING
    `;
    await loadBlacklistedIps().catch(() => {});
    await loadWhitelistedIdentifiers().catch(() => {});
    await sql`
      DELETE FROM web_security_threats
      WHERE target_endpoint IN ('/health', '/api/health', '/ping', '/api/ping', '/favicon.ico')
         OR target_endpoint LIKE '%/health%'
         OR (threat_type = 'AUTOMATED_SCRAPER_BOT' AND target_endpoint = '/health')
    `.catch(() => {});

    await sql`
      UPDATE web_users SET current_web_source = 'vercel'
      WHERE current_web_source IN ('web-locket', 'https://locket-dio.com', 'https://www.locket-dio.com', 'locket-dio.com');
    `.catch(() => {});
    await sql`
      UPDATE login_history SET web_source = 'vercel'
      WHERE web_source IN ('web-locket', 'https://locket-dio.com', 'https://www.locket-dio.com', 'locket-dio.com');
    `.catch(() => {});
    await sql`
      UPDATE user_sessions SET web_source = 'vercel'
      WHERE web_source IN ('web-locket', 'https://locket-dio.com', 'https://www.locket-dio.com', 'locket-dio.com');
    `.catch(() => {});

    await sql`
      INSERT INTO celebrity_profiles (uid, username, display_name, avatar_url, locket_url, country_code, enabled, sort_order, created_at, updated_at)
      SELECT uid, username, display_name, avatar_url, locket_url, country_code, enabled, sort_order, created_at, updated_at
      FROM locket_idols
      ON CONFLICT DO NOTHING;
    `.catch(() => {});
  })().catch((error) => {
    schemaPromise = null;
    throw error;
  });

  return schemaPromise;
}

function cleanOptional(value, maxLength = 320) {
  const clean = String(value || "").trim();
  return clean ? clean.slice(0, maxLength) : null;
}

function normalizeIdentity(decodedToken, verifiedProfile = null) {
  const uid = cleanOptional(decodedToken.uid || decodedToken.user_id, 160);
  if (!uid) throw new Error("Verified token has no user identifier");
  const email = cleanOptional(decodedToken.email || verifiedProfile?.email, 320)?.toLowerCase() || null;
  const profileName = [verifiedProfile?.firstName, verifiedProfile?.lastName]
    .map((value) => cleanOptional(value, 80))
    .filter(Boolean)
    .join(" ");
  return {
    uid,
    email,
    username: cleanOptional(verifiedProfile?.username || decodedToken.username, 120),
    displayName: cleanOptional(
      verifiedProfile?.displayName || profileName || decodedToken.name,
      160,
    ),
    profilePicture: cleanOptional(
      verifiedProfile?.profilePicture || decodedToken.picture,
      1000,
    ),
    authProvider: cleanOptional(decodedToken.firebase?.sign_in_provider, 80) || "locket-firebase",
  };
}

function shouldRecordLoginHistory(eventType) {
  return eventType === "login" || eventType === "resume";
}

async function getAccountStatus(uid) {
  await ensureUserActivitySchema();
  const sql = getSql();
  const rows = await sql`SELECT account_status FROM web_users WHERE uid = ${uid} LIMIT 1`;
  return rows[0]?.account_status || "active";
}

async function upsertSession({ identity, sessionId, eventType, loginMethod, context, build, gps }) {
  await ensureUserActivitySchema();
  const sql = getSql();
  const isLogin = eventType === "login";
  const recordsHistory = shouldRecordLoginHistory(eventType);
  const method = cleanOptional(loginMethod, 40) || "unknown";
  const historyMethod = eventType === "resume" ? "session-resume" : method;
  const version = cleanOptional(build?.version, 40);
  const buildId = cleanOptional(build?.buildId, 120);
  const commitHash = cleanOptional(build?.commitHash, 80);
  const gpsCoord = cleanOptional(String(gps || ""), 120);

  await sql`
    INSERT INTO web_users (
      uid, email, username, display_name, profile_picture, auth_provider,
      login_method, account_status, last_login_at, last_seen_at,
      current_web_source, ip_address, browser, os, gps_coordinates, updated_at
    ) VALUES (
      ${identity.uid}, ${identity.email}, ${identity.username}, ${identity.displayName},
      ${identity.profilePicture}, ${identity.authProvider}, ${method}, 'active',
      ${isLogin ? new Date() : null}, NOW(), ${context.webSource}, ${context.ipAddress !== 'Không xác định' ? context.ipAddress : null}, ${context.browser !== 'Không xác định' ? context.browser : null}, ${context.os !== 'Không xác định' ? context.os : null}, ${gpsCoord}, NOW()
    )
    ON CONFLICT (uid) DO UPDATE SET
      email = COALESCE(EXCLUDED.email, web_users.email),
      username = COALESCE(EXCLUDED.username, web_users.username),
      display_name = COALESCE(EXCLUDED.display_name, web_users.display_name),
      profile_picture = COALESCE(EXCLUDED.profile_picture, web_users.profile_picture),
      auth_provider = EXCLUDED.auth_provider,
      login_method = CASE WHEN ${isLogin} THEN EXCLUDED.login_method ELSE web_users.login_method END,
      last_login_at = CASE WHEN ${isLogin} THEN NOW() ELSE web_users.last_login_at END,
      last_seen_at = NOW(),
      current_web_source = EXCLUDED.current_web_source,
      ip_address = COALESCE(EXCLUDED.ip_address, web_users.ip_address),
      browser = COALESCE(EXCLUDED.browser, web_users.browser),
      os = COALESCE(EXCLUDED.os, web_users.os),
      gps_coordinates = COALESCE(EXCLUDED.gps_coordinates, web_users.gps_coordinates),
      updated_at = NOW()
  `;

  const accountStatus = await getAccountStatus(identity.uid);
  if (accountStatus === "locked") {
    const error = new Error("Website account is locked");
    error.code = "ACCOUNT_LOCKED";
    throw error;
  }

  if (eventType === "resume" && sessionId) {
    const check = await sql`SELECT status FROM user_sessions WHERE session_id = ${sessionId} LIMIT 1`;
    if (check[0]?.status === 'revoked') {
      const error = new Error("Session has been revoked");
      error.code = "SESSION_REVOKED";
      throw error;
    }
  }

  await sql`
    INSERT INTO user_sessions (session_id, user_uid, web_source, started_at, last_seen_at, ended_at, status)
    VALUES (${sessionId}, ${identity.uid}, ${context.webSource}, NOW(), NOW(), NULL, 'active')
    ON CONFLICT (session_id) DO UPDATE SET
      last_seen_at = NOW(),
      ended_at = NULL,
      status = 'active',
      web_source = EXCLUDED.web_source
    WHERE user_sessions.user_uid = EXCLUDED.user_uid
  `;

  if (recordsHistory) {
    await sql`
      INSERT INTO login_history (
        uid, session_id, ip_address, country, region, city, browser,
        browser_version, os, device, login_method, web_source,
        web_version, build_id, commit_hash, gps_coordinates, created_at, last_seen_at
      ) VALUES (
        ${identity.uid}, ${sessionId}, ${context.ipAddress}, ${context.country},
        ${context.region}, ${context.city}, ${context.browser}, ${context.browserVersion},
        ${context.os}, ${context.device}, ${historyMethod}, ${context.webSource},
        ${version}, ${buildId}, ${commitHash}, ${gpsCoord}, NOW(), NOW()
      )
      ON CONFLICT (session_id) WHERE session_id IS NOT NULL DO UPDATE SET
        last_seen_at = NOW(),
        gps_coordinates = COALESCE(EXCLUDED.gps_coordinates, login_history.gps_coordinates)
      WHERE login_history.uid = EXCLUDED.uid
    `;
  }

  return { accountStatus };
}

async function heartbeatSession({ uid, sessionId, webSource, gps }) {
  await ensureUserActivitySchema();
  const accountStatus = await getAccountStatus(uid);
  if (accountStatus === "locked") {
    const error = new Error("Website account is locked");
    error.code = "ACCOUNT_LOCKED";
    throw error;
  }
  const sql = getSql();
  const gpsCoord = cleanOptional(String(gps || ""), 120);
  const check = await sql`SELECT status FROM user_sessions WHERE session_id = ${sessionId} AND user_uid = ${uid} LIMIT 1`;
  if (check[0]?.status === 'revoked') {
    const error = new Error("Session has been revoked");
    error.code = "SESSION_REVOKED";
    throw error;
  }
  await sql`
    INSERT INTO web_users (uid, auth_provider, account_status, last_seen_at, current_web_source, gps_coordinates, updated_at)
    VALUES (${uid}, 'locket-firebase', 'active', NOW(), ${webSource || 'web-locket'}, ${gpsCoord}, NOW())
    ON CONFLICT (uid) DO UPDATE SET
      last_seen_at = NOW(),
      current_web_source = COALESCE(EXCLUDED.current_web_source, web_users.current_web_source),
      gps_coordinates = COALESCE(EXCLUDED.gps_coordinates, web_users.gps_coordinates),
      updated_at = NOW()
  `;
  await sql`
    INSERT INTO user_sessions (session_id, user_uid, web_source, started_at, last_seen_at, status)
    VALUES (${sessionId}, ${uid}, ${webSource || 'web-locket'}, NOW(), NOW(), 'active')
    ON CONFLICT (session_id) DO UPDATE SET
      last_seen_at = NOW(), status = 'active', ended_at = NULL, web_source = EXCLUDED.web_source
    WHERE user_sessions.user_uid = ${uid}
  `;
  await sql`
    UPDATE login_history SET last_seen_at = NOW(), gps_coordinates = COALESCE(${gpsCoord}, gps_coordinates)
    WHERE session_id = ${sessionId} AND uid = ${uid}
  `;
}

async function endSession({ uid, sessionId }) {
  await ensureUserActivitySchema();
  const sql = getSql();
  await sql`
    UPDATE user_sessions
    SET ended_at = NOW(), last_seen_at = NOW(), status = 'logged_out'
    WHERE session_id = ${sessionId} AND user_uid = ${uid}
  `;
  await sql`
    UPDATE login_history SET ended_at = NOW(), last_seen_at = NOW()
    WHERE session_id = ${sessionId} AND uid = ${uid}
  `;
  await sql`
    UPDATE web_users SET last_logout_at = NOW(), last_seen_at = NOW(), updated_at = NOW()
    WHERE uid = ${uid}
  `;
}

async function listWebUsers({ search = "", limit = 50, offset = 0 }) {
  await ensureUserActivitySchema();
  const sql = getSql();
  const normalizedSearch = cleanOptional(search, 160)?.toLowerCase() || "";
  const pattern = `%${normalizedSearch}%`;
  const rows = await sql`
    SELECT
      u.uid, u.internal_id, u.email, u.username, u.display_name,
      u.profile_picture, u.auth_provider, u.login_method, u.account_status,
      u.created_at, u.last_login_at, u.last_seen_at, u.last_logout_at,
      u.current_web_source, u.gps_coordinates,
      COALESCE(ro.role, 'user') AS role,
      COUNT(*) OVER()::int AS total_count,
      COALESCE(active.active_sessions, 0)::int AS active_sessions,
      COALESCE(latest.ip_address, u.ip_address) AS ip_address, latest.country, latest.region, latest.city,
      COALESCE(latest.browser, u.browser) AS browser, latest.browser_version, COALESCE(latest.os, u.os) AS os, latest.device,
      latest.login_method AS latest_login_method,
      COALESCE(latest.web_source, u.current_web_source) AS latest_web_source,
      latest.web_version, latest.build_id, latest.commit_hash,
      COALESCE(latest.gps_coordinates, u.gps_coordinates) AS latest_gps_coordinates,
      COALESCE(latest.created_at, u.last_seen_at, u.last_login_at) AS latest_login_event_at,
      latest.ended_at AS latest_session_ended_at
    FROM web_users u
    LEFT JOIN LATERAL (
      SELECT r.role FROM admin_roles r WHERE r.uid = u.uid LIMIT 1
    ) ro ON TRUE
    LEFT JOIN LATERAL (
      SELECT COUNT(*)::int AS active_sessions
      FROM user_sessions s
      WHERE s.user_uid = u.uid
        AND s.status = 'active'
        AND s.ended_at IS NULL
        AND s.last_seen_at >= NOW() - (${ONLINE_WINDOW_SECONDS} * INTERVAL '1 second')
    ) active ON TRUE
    LEFT JOIN LATERAL (
      SELECT h.* FROM login_history h
      WHERE h.uid = u.uid
      ORDER BY h.created_at DESC
      LIMIT 1
    ) latest ON TRUE
    WHERE ${normalizedSearch === ""}
      OR LOWER(COALESCE(u.email, '')) LIKE ${pattern}
      OR LOWER(COALESCE(u.username, '')) LIKE ${pattern}
      OR LOWER(COALESCE(u.display_name, '')) LIKE ${pattern}
      OR LOWER(u.uid) LIKE ${pattern}
    ORDER BY u.last_seen_at DESC NULLS LAST, u.created_at DESC
    LIMIT ${limit + 1} OFFSET ${offset}
  `;
  const hasMore = rows.length > limit;
  return {
    users: rows.slice(0, limit),
    total: rows[0]?.total_count || 0,
    nextOffset: hasMore ? offset + limit : null,
    onlineWindowSeconds: ONLINE_WINDOW_SECONDS,
  };
}

async function getLoginHistory(uid, limit = 100) {
  await ensureUserActivitySchema();
  const sql = getSql();
  return sql`
    SELECT event_id, session_id, ip_address, country, region, city,
      browser, browser_version, os, device, login_method, web_source,
      web_version, build_id, commit_hash, gps_coordinates, created_at, last_seen_at, ended_at
    FROM login_history
    WHERE uid = ${uid}
    ORDER BY created_at DESC
    LIMIT ${limit}
  `;
}

async function getWebUser(uid) {
  await ensureUserActivitySchema();
  const sql = getSql();
  const rows = await sql`
    SELECT uid, email, display_name, account_status
    FROM web_users WHERE uid = ${uid} LIMIT 1
  `;
  return rows[0] || null;
}

async function clearLoginHistory(uid) {
  await ensureUserActivitySchema();
  const sql = getSql();
  const rows = await sql`DELETE FROM login_history WHERE uid = ${uid} RETURNING event_id`;
  return rows.length;
}

async function setAccountStatus(uid, status) {
  await ensureUserActivitySchema();
  const sql = getSql();
  const rows = await sql`
    UPDATE web_users SET account_status = ${status}, updated_at = NOW()
    WHERE uid = ${uid} RETURNING uid
  `;
  return rows.length > 0;
}

async function writeAudit({ adminUid, role = null, action, targetUid = null, details = null, ipAddress = null, webSource = null, status = 'success' }) {
  await ensureUserActivitySchema();
  const sql = getSql();
  await sql`
    INSERT INTO admin_audit_log (admin_uid, role, action, target_uid, details, ip_address, web_source, status)
    VALUES (${adminUid}, ${role}, ${action}, ${targetUid}, ${cleanOptional(details, 500)}, ${ipAddress}, ${webSource}, ${status})
  `;
}

async function getUserRole(uid, email) {
  await ensureUserActivitySchema();
  const sql = getSql();
  const normalizedEmail = String(email || "").trim().toLowerCase();
  const isRootAdmin = getAdminLocketUids().has(uid) || (normalizedEmail && getAdminLocketEmails().has(normalizedEmail));
  if (isRootAdmin) {
    try {
      await sql`INSERT INTO admin_roles (uid, role, assigned_by) VALUES (${uid}, 'super_admin', 'bootstrap') ON CONFLICT (uid) DO UPDATE SET role = 'super_admin' WHERE admin_roles.uid = ${uid}`;
    } catch (err) {
      console.warn("Failed to bootstrap super_admin in admin_roles:", err.message);
    }
    return 'super_admin';
  }
  const rows = await sql`SELECT role FROM admin_roles WHERE uid = ${uid} LIMIT 1`;
  if (rows.length > 0 && rows[0]?.role) {
    return rows[0].role;
  }
  return 'user';
}

async function setUserRole(targetUid, newRole, assignedByUid) {
  await ensureUserActivitySchema();
  const sql = getSql();
  const rows = await sql`
    INSERT INTO admin_roles (uid, role, assigned_by, updated_at)
    VALUES (${targetUid}, ${newRole}, ${assignedByUid}, NOW())
    ON CONFLICT (uid) DO UPDATE SET
      role = EXCLUDED.role,
      assigned_by = EXCLUDED.assigned_by,
      updated_at = NOW()
    RETURNING uid, role
  `;
  return rows[0] || null;
}

async function revokeUserSessions(uid) {
  await ensureUserActivitySchema();
  const sql = getSql();
  const rows = await sql`
    UPDATE user_sessions
    SET ended_at = NOW(), status = 'revoked'
    WHERE user_uid = ${uid} AND (ended_at IS NULL OR status = 'active')
    RETURNING session_id
  `;
  await sql`
    UPDATE login_history SET ended_at = NOW()
    WHERE uid = ${uid} AND ended_at IS NULL
  `;
  return rows.length;
}

async function createAdminSession(uid, tokenHash, ttlMinutes = 30) {
  await ensureUserActivitySchema();
  const sql = getSql();
  await sql`
    INSERT INTO admin_sessions (token_hash, uid, expires_at, created_at)
    VALUES (${tokenHash}, ${uid}, NOW() + (${ttlMinutes} * INTERVAL '1 minute'), NOW())
    ON CONFLICT (token_hash) DO UPDATE SET
      expires_at = EXCLUDED.expires_at,
      uid = EXCLUDED.uid
  `;
}

async function verifyAdminSessionToken(uid, tokenHash, extendMinutes = 30) {
  await ensureUserActivitySchema();
  const sql = getSql();
  const rows = await sql`
    SELECT uid FROM admin_sessions
    WHERE token_hash = ${tokenHash} AND uid = ${uid} AND expires_at > NOW()
    LIMIT 1
  `;
  if (rows.length > 0) {
    await sql`
      UPDATE admin_sessions SET expires_at = NOW() + (${extendMinutes} * INTERVAL '1 minute')
      WHERE token_hash = ${tokenHash}
    `.catch(() => {});
    return true;
  }
  return false;
}

function hashPin(pin) {
  const crypto = require("node:crypto");
  return crypto.createHash("sha256").update(String(pin || "").trim() + "_huy_locket_pin_salt").digest("hex");
}

async function checkAdminPinSet(uid) {
  if (!uid) return false;
  await ensureUserActivitySchema();
  const sql = getSql();
  const rows = await sql`SELECT pin_hash FROM admin_roles WHERE uid = ${uid} LIMIT 1`;
  return Boolean(rows[0]?.pin_hash);
}

async function verifyAdminPin(uid, pin) {
  if (!uid || !pin) return false;
  await ensureUserActivitySchema();
  const sql = getSql();
  const rows = await sql`SELECT pin_hash FROM admin_roles WHERE uid = ${uid} LIMIT 1`;
  const storedHash = rows[0]?.pin_hash;
  if (!storedHash) return false;
  return hashPin(pin) === storedHash;
}

async function setAdminPin(uid, pin, role = "super_admin") {
  if (!uid || !pin) throw new Error("Missing uid or pin");
  await ensureUserActivitySchema();
  const sql = getSql();
  const hashed = hashPin(pin);
  await sql`
    INSERT INTO admin_roles (uid, role, pin_hash, assigned_by, updated_at)
    VALUES (${uid}, ${role}, ${hashed}, 'self', NOW())
    ON CONFLICT (uid) DO UPDATE SET pin_hash = EXCLUDED.pin_hash, updated_at = NOW()
  `;
  return true;
}

async function listAuditLogs({ action = "", adminUid = "", limit = 100, offset = 0 }) {
  await ensureUserActivitySchema();
  const sql = getSql();
  const patternAction = action ? `%${action}%` : null;
  const patternAdmin = adminUid ? `%${adminUid}%` : null;
  const rows = await sql`
    SELECT id, admin_uid, role, action, target_uid, details, ip_address, web_source, status, created_at,
           COUNT(*) OVER()::int AS total_count
    FROM admin_audit_log
    WHERE (${patternAction === null} OR action ILIKE ${patternAction})
      AND (${patternAdmin === null} OR admin_uid ILIKE ${patternAdmin})
    ORDER BY created_at DESC
    LIMIT ${limit} OFFSET ${offset}
  `;
  return {
    logs: rows,
    total: rows[0]?.total_count || 0
  };
}

async function listReportedContent({ status = "", limit = 50 }) {
  await ensureUserActivitySchema();
  const sql = getSql();
  const patternStatus = status ? status : null;
  const rows = await sql`
    SELECT * FROM reported_content
    WHERE (${patternStatus === null} OR status = ${patternStatus})
    ORDER BY created_at DESC
    LIMIT ${limit}
  `;
  return rows;
}

async function resolveReport({ id, actionTaken, resolvedBy }) {
  await ensureUserActivitySchema();
  const sql = getSql();
  const rows = await sql`
    UPDATE reported_content
    SET status = 'resolved', action_taken = ${actionTaken}, resolved_by = ${resolvedBy}, resolved_at = NOW()
    WHERE id = ${id} RETURNING id
  `;
  return rows.length > 0;
}

async function recordServerUserActivity({ user, req, eventType = 'touch', loginMethod = 'unknown' }) {
  if (!hasActivityDatabase() || !user) return;
  try {
    await ensureUserActivitySchema();
    const sql = getSql();
    const uid = cleanOptional(user.uid || user.localId || user.user_id, 160);
    if (!uid) return;

    const email = cleanOptional(user.email || null, 320)?.toLowerCase() || null;
    const displayName = cleanOptional(user.displayName || user.name || null, 160);
    const picture = cleanOptional(user.picture || user.profilePicture || null, 1000);

    let webSource = "web-locket";
    const ctx = req ? getRequestContext(req) : null;
    if (ctx && ctx.webSource) {
      webSource = ctx.webSource;
    }
    const ip = ctx?.ipAddress && ctx.ipAddress !== "Không xác định" ? ctx.ipAddress : null;
    const browser = ctx?.browser && ctx.browser !== "Không xác định" ? ctx.browser : null;
    const os = ctx?.os && ctx.os !== "Không xác định" ? ctx.os : null;
    const device = ctx?.device || null;

    const isLogin = eventType === "login";
    await sql`
      INSERT INTO web_users (
        uid, email, display_name, profile_picture, auth_provider,
        login_method, account_status, last_login_at, last_seen_at,
        current_web_source, ip_address, browser, os, updated_at
      ) VALUES (
        ${uid}, ${email}, ${displayName}, ${picture}, 'locket-firebase',
        ${cleanOptional(loginMethod, 40) || 'unknown'}, 'active', ${isLogin ? new Date() : null}, NOW(),
        ${webSource}, ${ip}, ${browser}, ${os}, NOW()
      )
      ON CONFLICT (uid) DO UPDATE SET
        email = COALESCE(EXCLUDED.email, web_users.email),
        display_name = COALESCE(EXCLUDED.display_name, web_users.display_name),
        profile_picture = COALESCE(EXCLUDED.profile_picture, web_users.profile_picture),
        login_method = CASE WHEN ${isLogin} THEN EXCLUDED.login_method ELSE web_users.login_method END,
        last_login_at = CASE WHEN ${isLogin} THEN NOW() ELSE web_users.last_login_at END,
        last_seen_at = NOW(),
        current_web_source = COALESCE(EXCLUDED.current_web_source, web_users.current_web_source),
        ip_address = COALESCE(EXCLUDED.ip_address, web_users.ip_address),
        browser = COALESCE(EXCLUDED.browser, web_users.browser),
        os = COALESCE(EXCLUDED.os, web_users.os),
        updated_at = NOW()
    `;

    if (ctx && (ip || browser || os)) {
      await sql`
        INSERT INTO login_history (
          uid, session_id, ip_address, country, region, city, browser,
          browser_version, os, device, login_method, web_source,
          web_version, created_at, last_seen_at
        )
        SELECT
          ${uid}, NULL, ${ctx.ipAddress || 'Không xác định'}, ${ctx.country || 'Không xác định'},
          ${ctx.region || 'Không xác định'}, ${ctx.city || 'Không xác định'}, ${ctx.browser || 'Không xác định'},
          ${ctx.browserVersion || '-'}, ${ctx.os || 'Không xác định'}, ${device || 'Không xác định'},
          ${cleanOptional(loginMethod, 40) || 'api-touch'}, ${webSource}, '-', NOW(), NOW()
        WHERE NOT EXISTS (
          SELECT 1 FROM login_history WHERE uid = ${uid} AND last_seen_at >= NOW() - INTERVAL '1 hour'
        )
      `;
    }
  } catch (error) {
    // Silent fail to avoid interrupting API responses
  }
}

async function purgeBotUsers(currentAdminUid = null) {
  await ensureUserActivitySchema();
  const sql = getSql();
  const { getAdminLocketUids, getAdminLocketEmails } = require("./locketAdminVerifier");

  const users = await sql`
    SELECT
      u.uid, u.email, u.display_name, u.account_status,
      COALESCE(ro.role, 'user') AS role,
      COALESCE(latest.ip_address, u.ip_address) AS ip_address,
      COALESCE(latest.browser, u.browser) AS browser,
      COALESCE(latest.device, u.os, '') AS device
    FROM web_users u
    LEFT JOIN LATERAL (
      SELECT r.role FROM admin_roles r WHERE r.uid = u.uid LIMIT 1
    ) ro ON TRUE
    LEFT JOIN LATERAL (
      SELECT h.ip_address, h.browser, h.device FROM login_history h
      WHERE h.uid = u.uid
      ORDER BY h.created_at DESC
      LIMIT 1
    ) latest ON TRUE
    WHERE u.account_status != 'locked'
  `;

  const purgedList = [];
  for (const u of users) {
    if (u.uid === currentAdminUid || u.role === 'super_admin' || u.role === 'admin') continue;
    const normEmail = String(u.email || "").trim().toLowerCase();
    if (getAdminLocketUids().has(u.uid) || (normEmail && getAdminLocketEmails().has(normEmail))) continue;

    const ip = String(u.ip_address || "").trim();
    const browser = String(u.browser || "").trim().toLowerCase();
    const device = String(u.device || "").trim().toLowerCase();

    const isCloudIp = /^(54\.|3\.|18\.|13\.|52\.|50\.|23\.)/.test(ip);
    const isSuspiciousEmail = normEmail.startsWith("tiendai") || normEmail.includes("clone") || normEmail.includes("bot");

    // Chỉ trảm khi chắc chắn 100% là IP Máy chủ Cloud VPS hoặc Email dạng tool clone (không cào bằng những tài khoản thường cũ chưa ghi log trình duyệt)
    if (isCloudIp || isSuspiciousEmail) {
      await setAccountStatus(u.uid, "locked");
      await revokeUserSessions(u.uid);
      purgedList.push({ uid: u.uid, email: u.email, displayName: u.display_name, ip, reason: "Phát hiện Bot/Tool/VPS tự động" });
    }
  }

  return { purgedCount: purgedList.length, purgedUsers: purgedList };
}

// 1. Quyền Phát Sóng Thông Báo Toàn Cầu
async function setGlobalBroadcast(message, level = "info", active = true, targetUser = "ALL") {
  const sql = getSql();
  if (!sql) return { success: false, error: "Cơ sở dữ liệu chưa kết nối" };
  try {
    await ensureUserActivitySchema();
    const tUser = String(targetUser || "ALL").trim() || "ALL";
    let nextId = 1;
    try {
      const resId = await sql`SELECT COALESCE(MAX(id), 0) + 1 AS next_id FROM global_broadcasts`;
      nextId = Number(resId[0]?.next_id) || 1;
    } catch (e) {
      nextId = Math.floor(Date.now() / 1000);
    }
    await sql`
      INSERT INTO global_broadcasts (id, message, level, active, target_user, updated_at)
      VALUES (${nextId}, ${message}, ${level}, ${active}, ${tUser}, NOW())
    `;
    return { success: true, id: nextId, message, level, active, targetUser: tUser };
  } catch (err) {
    console.error("setGlobalBroadcast error:", err);
    return { success: false, error: err?.message || "Lỗi SQL khi đăng thông báo" };
  }
}

async function listGlobalBroadcasts() {
  const sql = getSql();
  if (!sql) return [];
  try {
    await ensureUserActivitySchema();
    const res = await sql`SELECT id, message, level, active, target_user, updated_at FROM global_broadcasts ORDER BY updated_at DESC LIMIT 50`;
    return res.map((row) => ({
      id: row.id,
      message: row.message,
      level: row.level,
      active: row.active,
      targetUser: row.target_user || "ALL",
      updatedAt: row.updated_at,
    }));
  } catch (e) {
    console.error("listGlobalBroadcasts error:", e);
    return [];
  }
}

async function toggleGlobalBroadcast(id, active) {
  const sql = getSql();
  if (!sql || !id) return { success: false };
  try {
    await ensureUserActivitySchema();
    await sql`UPDATE global_broadcasts SET active = ${Boolean(active)}, updated_at = NOW() WHERE id = ${Number(id)}`;
    return { success: true, id: Number(id), active: Boolean(active) };
  } catch (err) {
    return { success: false, error: err?.message };
  }
}

async function deleteGlobalBroadcast(id) {
  const sql = getSql();
  if (!sql || !id) return { success: false };
  try {
    await ensureUserActivitySchema();
    await sql`DELETE FROM global_broadcasts WHERE id = ${Number(id)}`;
    return { success: true, id: Number(id) };
  } catch (err) {
    return { success: false, error: err?.message };
  }
}

async function getGlobalBroadcast() {
  const sql = getSql();
  if (!sql) return { active: false, message: "", targetUser: "ALL", list: [] };
  try {
    await ensureUserActivitySchema();
    const res = await sql`SELECT id, message, level, active, target_user, updated_at FROM global_broadcasts WHERE active = TRUE ORDER BY updated_at DESC LIMIT 20`;
    const list = res.map((row) => ({ id: row.id, active: row.active, message: row.message, level: row.level, targetUser: row.target_user || "ALL", updatedAt: row.updated_at }));
    return list[0] ? { ...list[0], list } : { active: false, message: "", targetUser: "ALL", list: [] };
  } catch (err) {
    console.error("getGlobalBroadcast error:", err);
    return { active: false, message: "", targetUser: "ALL", list: [] };
  }
}


// 2.1. Quản lý Whitelist (Danh sách miễn trừ)
const whitelistedIdentifiersMemory = new Set();
async function loadWhitelistedIdentifiers() {
  const sql = getSql();
  if (!sql) return;
  try {
    const res = await sql`SELECT identifier FROM web_security_whitelist`;
    whitelistedIdentifiersMemory.clear();
    for (const row of res) {
      whitelistedIdentifiersMemory.add(row.identifier);
    }
  } catch {}
}

async function addWhitelist(identifier, type = "ip", added_by = "SUPER_ADMIN") {
  const sql = getSql();
  if (!sql || !identifier) return { success: false };
  await sql`
    INSERT INTO web_security_whitelist (identifier, type, added_by, created_at)
    VALUES (${identifier}, ${type}, ${added_by}, NOW())
    ON CONFLICT (identifier) DO NOTHING
  `;
  whitelistedIdentifiersMemory.add(identifier);
  return { success: true, identifier };
}

async function removeWhitelist(identifier) {
  const sql = getSql();
  if (!sql || !identifier) return { success: false };
  await sql`DELETE FROM web_security_whitelist WHERE identifier = ${identifier}`;
  whitelistedIdentifiersMemory.delete(identifier);
  return { success: true, identifier };
}

async function listWhitelist() {
  const sql = getSql();
  if (!sql) return [];
  return await sql`SELECT identifier, type, added_by, created_at FROM web_security_whitelist ORDER BY created_at DESC LIMIT 1000`;
}

function isWhitelisted(identifier) {
  if (!identifier) return false;
  return whitelistedIdentifiersMemory.has(identifier);
}


  // 2. Quyền Cấm Cửa Địa Chỉ IP Vĩnh Viễn
const blacklistedIpsMemory = new Set();
async function loadBlacklistedIps() {
  const sql = getSql();
  if (!sql) return;
  try {
    // WAF v2 used to persist heuristic bot detections forever. Retire only
    // those system-generated rows; explicit admin bans must stay intact.
    const retired = await sql`
      DELETE FROM ip_blacklist
      WHERE blocked_by = 'SYSTEM_WAF_v2'
      RETURNING ip_address
    `;
    if (retired.length > 0) {
      console.warn(`[Security] Retired ${retired.length} legacy automatic WAF IP ban(s)`);
    }
    const res = await sql`SELECT ip_address FROM ip_blacklist`;
    blacklistedIpsMemory.clear();
    for (const row of res) {
      blacklistedIpsMemory.add(row.ip_address);
    }
  } catch {}
}

async function addIpBlacklist(ip_address, reason = "Banned by Admin", blocked_by = "SUPER_ADMIN") {
  const sql = getSql();
  if (!sql || !ip_address || ip_address === "Không xác định") return { success: false };
  await sql`
    INSERT INTO ip_blacklist (ip_address, reason, blocked_by, created_at)
    VALUES (${ip_address}, ${reason}, ${blocked_by}, NOW())
    ON CONFLICT (ip_address) DO UPDATE SET reason = EXCLUDED.reason, blocked_by = EXCLUDED.blocked_by, created_at = NOW()
  `;
  blacklistedIpsMemory.add(ip_address);
  return { success: true, ip_address };
}

async function removeIpBlacklist(ip_address) {
  const sql = getSql();
  if (!sql || !ip_address) return { success: false };
  await sql`DELETE FROM ip_blacklist WHERE ip_address = ${ip_address}`;
  blacklistedIpsMemory.delete(ip_address);
  return { success: true, ip_address };
}

async function listBlacklistedIps() {
  const sql = getSql();
  if (!sql) return [];
  return await sql`SELECT ip_address, reason, blocked_by, created_at FROM ip_blacklist ORDER BY created_at DESC LIMIT 1000`;
}

function isIpBlacklisted(ip) {
  return blacklistedIpsMemory.has(ip);
}

// 3. Quyền Xóa Khởi Tử Vĩnh Viễn Từng Tài Khoản
async function nukeUserPermanently(uid) {
  const sql = getSql();
  if (!sql || !uid) return { success: false };
  await sql`DELETE FROM login_history WHERE uid = ${uid} OR user_uid = ${uid}`;
  await sql`DELETE FROM user_sessions WHERE uid = ${uid}`;
  await sql`DELETE FROM web_users WHERE uid = ${uid}`;
  return { success: true };
}

// 4. Cảm Biến Giám Sát Tài Nguyên & Thống Kê Máy Chủ
async function getServerHealthStats() {
  const os = require("os");
  const memory = process.memoryUsage();
  const procUptime = process.uptime();
  const osUptime = os.uptime ? os.uptime() : procUptime;

  const cpus = os.cpus ? os.cpus() : [];
  const cpuModel = cpus[0]?.model || "Intel/AMD Cloud vCPU";
  const cpuCores = cpus.length || 1;
  const cpuSpeed = cpus[0]?.speed ? `${cpus[0].speed} MHz` : "Standard Cloud MHz";
  const loadAvg = os.loadavg ? os.loadavg().map((n) => Number(n || 0).toFixed(2)).join(", ") : "N/A";

  const totalRamMb = os.totalmem ? Math.round(os.totalmem() / (1024 * 1024)) : 0;
  const freeRamMb = os.freemem ? Math.round(os.freemem() / (1024 * 1024)) : 0;

  const sql = getSql();
  const t0 = Date.now();
  let dbStatus = "DISCONNECTED";
  let dbVersion = "PostgreSQL Neon Cloud";
  let dbSize = "N/A";
  let dbTables = 0;
  let dbConnections = { active: 0, total: 0 };
  let dbRecords = { users: 0, sessions: 0, audit: 0, blacklistedIps: 0 };
  let dbLatencyMs = 0;

  if (sql) {
    try {
      const vRes = await sql`SELECT version();`;
      if (vRes[0]?.version) {
        dbStatus = "CONNECTED (Neon Serverless)";
        const vParts = String(vRes[0].version).split(" ");
        dbVersion = `${vParts[0]} ${vParts[1] || ""}`.trim();
      }
      try {
        const szRes = await sql`SELECT pg_size_pretty(pg_database_size(current_database())) as size;`;
        dbSize = szRes[0]?.size || "N/A";
      } catch {}
      try {
        const tbRes = await sql`SELECT count(*) as count FROM information_schema.tables WHERE table_schema='public';`;
        dbTables = Number(tbRes[0]?.count) || 0;
      } catch {}
      try {
        const connRes = await sql`SELECT count(*) as total, count(*) filter (where state = 'active') as active FROM pg_stat_activity WHERE datname = current_database();`;
        dbConnections = { total: Number(connRes[0]?.total) || 1, active: Number(connRes[0]?.active) || 1 };
      } catch {}
      try {
        const uC = await sql`SELECT count(*) as c FROM web_users;`;
        const sC = await sql`SELECT count(*) as c FROM user_sessions;`;
        const aC = await sql`SELECT count(*) as c FROM admin_audit_log;`;
        const iC = await sql`SELECT count(*) as c FROM ip_blacklist;`;
        dbRecords = {
          users: Number(uC[0]?.c) || 0,
          sessions: Number(sC[0]?.c) || 0,
          audit: Number(aC[0]?.c) || 0,
          blacklistedIps: Number(iC[0]?.c) || 0,
        };
      } catch {}
      dbLatencyMs = Date.now() - t0;
    } catch (err) {
      dbStatus = `ERROR: ${err?.message || "Lỗi kết nối DB"}`;
    }
  }

  return {
    status: "OPTIMAL (Huy Locket Shield Active)",
    pid: process.pid,
    uptimeSeconds: Math.floor(procUptime),
    osUptimeSeconds: Math.floor(osUptime),
    memoryRssMb: Math.round(memory.rss / (1024 * 1024)),
    memoryHeapUsedMb: Math.round(memory.heapUsed / (1024 * 1024)),
    memoryHeapTotalMb: Math.round(memory.heapTotal / (1024 * 1024)),
    totalOsRamMb: totalRamMb,
    freeOsRamMb: freeRamMb,
    cpuModel,
    cpuCores,
    cpuSpeed,
    loadAvg,
    nodeVersion: process.version,
    platform: `${process.platform} (${process.arch})`,
    environment: process.env.RAILWAY_ENVIRONMENT || process.env.NODE_ENV || "production",
    db: {
      status: dbStatus,
      version: dbVersion,
      size: dbSize,
      tables: dbTables,
      connections: dbConnections,
      records: dbRecords,
      latencyMs: dbLatencyMs,
    },
    measuredAt: Date.now(),
  };
}

// 5. Quyền kiểm tra trạng thái khôi phục Mật Khẩu (Password Recovery Status)
function getUserPasswordRecoveryStatus(email) {
  return {
    email: email || "Chưa gắn email",
    canResetViaFirebase: Boolean(email && email.includes("@")),
    secureDirectLinkSupported: true,
    policy: "Bảo vệ bởi Mã hóa chuẩn Locket Firebase. Không lưu bản rõ, nhưng hỗ trợ kích hoạt cổng đổi mật khẩu KHẨN CẤP khi người dùng quên.",
  };
}

async function healIpLocationInDb(ipAddress, { city, region, country }) {
  if (!ipAddress || ipAddress === "Không xác định" || !city || city === "Không xác định") return;
  const sql = getSql();
  if (!sql) return;
  try {
    const imprecise = ['Không xác định', '', 'Unknown', 'Hanoi', 'Hà Nội', 'Ho Chi Minh City', 'Hồ Chí Minh', 'Ho Chi Minh'];
    await sql`
      UPDATE login_history
      SET city = ${city}, region = ${region}, country = ${country}
      WHERE ip_address = ${ipAddress} AND (city IS NULL OR city = ANY(${imprecise}))
    `;
    await sql`
      UPDATE user_sessions
      SET city = ${city}, region = ${region}, country = ${country}
      WHERE ip_address = ${ipAddress} AND (city IS NULL OR city = ANY(${imprecise}))
    `;
  } catch (e) {
    console.warn("Failed healing IP location in DB:", e?.message || e);
  }
}

// 6. Cảm Biến Giám Sát Hành Vi Người Dùng Trên Website (Real-time Action Surveillance)
async function recordWebUserAction({ user, req, actionType, actionTitle, details = null }) {
  if (!hasActivityDatabase() || !user || !actionType || !actionTitle) return null;
  try {
    await ensureUserActivitySchema();
    const sql = getSql();
    const uid = cleanOptional(user.uid || user.localId || user.user_id, 160);
    if (!uid) return null;
    const email = cleanOptional(user.email || null, 320)?.toLowerCase() || null;
    const displayName = cleanOptional(user.displayName || user.name || null, 160);
    const picture = cleanOptional(user.picture || user.profilePicture || null, 1000);
    
    const ctx = req ? getRequestContext(req) : null;
    const ip = ctx?.ipAddress && ctx.ipAddress !== "Không xác định" ? ctx.ipAddress : null;
    const browser = ctx?.browser && ctx.browser !== "Không xác định" ? ctx.browser : null;
    const device = ctx?.device || null;

    await sql`
      INSERT INTO web_user_actions (uid, email, display_name, profile_picture, action_type, action_title, details, ip_address, device, browser, created_at)
      VALUES (${uid}, ${email}, ${displayName}, ${picture}, ${cleanOptional(actionType, 50)}, ${cleanOptional(actionTitle, 200)}, ${cleanOptional(details, 500)}, ${ip}, ${device}, ${browser}, NOW())
    `;
    return true;
  } catch (err) {
    console.error("recordWebUserAction error:", err?.message || err);
    return false;
  }
}

async function listWebUserActions({ uid = "", actionType = "", search = "", limit = 150, offset = 0 } = {}) {
  await ensureUserActivitySchema();
  const sql = getSql();
  const patternUid = uid ? `%${uid}%` : null;
  const patternType = actionType ? `%${actionType}%` : null;
  const patternSearch = search ? `%${cleanOptional(search, 160).toLowerCase()}%` : null;
  const rows = await sql`
    SELECT a.id, a.uid,
           COALESCE(u.email, a.email, 'Không có email') AS email,
           COALESCE(u.display_name, a.display_name, 'Thành viên Locket') AS display_name,
           COALESCE(u.profile_picture, a.profile_picture) AS profile_picture,
           a.action_type, a.action_title, a.details, a.ip_address, a.device, a.browser, a.created_at,
           COUNT(*) OVER()::int AS total_count
    FROM web_user_actions a
    LEFT JOIN web_users u ON a.uid = u.uid
    WHERE (${patternUid === null} OR a.uid ILIKE ${patternUid})
      AND (${patternType === null} OR a.action_type ILIKE ${patternType})
      AND (${patternSearch === null} OR LOWER(COALESCE(u.email, a.email, '')) LIKE ${patternSearch} OR LOWER(COALESCE(u.display_name, a.display_name, '')) LIKE ${patternSearch} OR LOWER(a.action_title) LIKE ${patternSearch})
    ORDER BY a.created_at DESC
    LIMIT ${limit} OFFSET ${offset}
  `;
  return {
    actions: rows,
    total: rows[0]?.total_count || 0,
  };
}

async function clearWebUserActions(uid = null) {
  await ensureUserActivitySchema();
  const sql = getSql();
  if (uid) {
    await sql`DELETE FROM web_user_actions WHERE uid = ${uid}`;
  } else {
    await sql`DELETE FROM web_user_actions`;
  }
  return true;
}

// 7. Cảm Biến Tường Lửa & Phát Hiện Tấn Công Web (Real-time WAF & Security IDS)
async function recordSecurityThreat({
  threatType,
  severity,
  targetEndpoint = null,
  attackerIp = null,
  userUid = null,
  userEmail = null,
  userAgent = null,
  details = null,
  payloadSample = null,
  status = "BLOCKED",
} = {}) {
  if (!hasActivityDatabase()) return false;
  try {
    await ensureUserActivitySchema();
    const sql = getSql();
    await sql`
      INSERT INTO web_security_threats (threat_type, severity, target_endpoint, attacker_ip, user_uid, user_email, user_agent, details, payload_sample, status, created_at)
      VALUES (${cleanOptional(threatType, 50)}, ${cleanOptional(severity, 20)}, ${cleanOptional(targetEndpoint, 250)}, ${cleanOptional(attackerIp, 100)}, ${cleanOptional(userUid, 150)}, ${cleanOptional(userEmail, 320)}, ${cleanOptional(userAgent, 500)}, ${cleanOptional(details, 800)}, ${cleanOptional(payloadSample, 500)}, ${cleanOptional(status, 30)}, NOW())
    `;
    return true;
  } catch (err) {
    console.error("recordSecurityThreat error:", err?.message || err);
    return false;
  }
}

async function listSecurityThreats({ threatType = "", severity = "", search = "", limit = 150, offset = 0 } = {}) {
  await ensureUserActivitySchema();
  const sql = getSql();
  const patternType = threatType ? `%${threatType}%` : null;
  const patternSev = severity ? `%${severity}%` : null;
  const patternSearch = search ? `%${cleanOptional(search, 160).toLowerCase()}%` : null;
  const rows = await sql`
    SELECT t.id, t.threat_type, t.severity, t.target_endpoint, t.attacker_ip, t.user_uid, t.user_email, t.user_agent, t.details, t.payload_sample, t.status, t.created_at,
           COUNT(*) OVER()::int AS total_count
    FROM web_security_threats t
    WHERE (${patternType === null} OR t.threat_type ILIKE ${patternType})
      AND (${patternSev === null} OR t.severity ILIKE ${patternSev})
      AND (${patternSearch === null} OR LOWER(COALESCE(t.attacker_ip, '')) LIKE ${patternSearch} OR LOWER(COALESCE(t.details, '')) LIKE ${patternSearch} OR LOWER(COALESCE(t.target_endpoint, '')) LIKE ${patternSearch})
    ORDER BY t.created_at DESC
    LIMIT ${limit} OFFSET ${offset}
  `;
  return {
    threats: rows,
    total: rows[0]?.total_count || 0,
  };
}

async function clearSecurityThreats(id = null) {
  await ensureUserActivitySchema();
  const sql = getSql();
  if (id && id !== "ALL" && id !== "all") {
    await sql`DELETE FROM web_security_threats WHERE id = ${Number(id)}`;
  } else {
    await sql`DELETE FROM web_security_threats`;
  }
  return true;
}

async function getAdmin2FAInfo(uid) {
  await ensureUserActivitySchema();
  const sql = getSql();
  const rows = await sql`
    SELECT two_factor_secret, is_two_factor_enabled
    FROM web_users
    WHERE uid = ${uid}
    LIMIT 1
  `;
  return rows[0] || { two_factor_secret: null, is_two_factor_enabled: false };
}

async function setAdmin2FASecret(uid, secret, enabled = false) {
  await ensureUserActivitySchema();
  const sql = getSql();
  await sql`
    INSERT INTO web_users (uid, auth_provider, account_status, two_factor_secret, is_two_factor_enabled, created_at, updated_at)
    VALUES (${uid}, 'locket-firebase', 'active', ${secret}, ${enabled}, NOW(), NOW())
    ON CONFLICT (uid) DO UPDATE
    SET two_factor_secret = EXCLUDED.two_factor_secret,
        is_two_factor_enabled = EXCLUDED.is_two_factor_enabled,
        updated_at = NOW()
  `;
  return true;
}

async function setAdmin2FAEnabled(uid, enabled = true) {
  await ensureUserActivitySchema();
  const sql = getSql();
  await sql`
    INSERT INTO web_users (uid, auth_provider, account_status, is_two_factor_enabled, created_at, updated_at)
    VALUES (${uid}, 'locket-firebase', 'active', ${enabled}, NOW(), NOW())
    ON CONFLICT (uid) DO UPDATE
    SET is_two_factor_enabled = EXCLUDED.is_two_factor_enabled,
        updated_at = NOW()
  `;
  return true;
}

module.exports = {
  ONLINE_WINDOW_SECONDS,
  getAdmin2FAInfo,
  setAdmin2FASecret,
  setAdmin2FAEnabled,
  addIpBlacklist,
    addWhitelist,
    listWhitelist,
    removeWhitelist,
    isWhitelisted,
    loadWhitelistedIdentifiers,
  checkAdminPinSet,
  clearLoginHistory,
  clearWebUserActions,
  clearSecurityThreats,
  createAdminSession,
  endSession,
  ensureUserActivitySchema,
  getAccountStatus,
  getGlobalBroadcast,
  getLoginHistory,
  getServerHealthStats,
  getUserPasswordRecoveryStatus,
  getUserRole,
  getWebUser,
  hasActivityDatabase,
  healIpLocationInDb,
  heartbeatSession,

  isIpBlacklisted,
  listAuditLogs,
  listBlacklistedIps,
  listReportedContent,
  listSecurityThreats,
  listWebUserActions,
  listWebUsers,
  loadBlacklistedIps,
  normalizeIdentity,
  nukeUserPermanently,
  purgeBotUsers,
  recordSecurityThreat,
  recordServerUserActivity,
  recordWebUserAction,
  removeIpBlacklist,
  resolveReport,
  revokeUserSessions,
  setAccountStatus,
  setAdminPin,
  setGlobalBroadcast,
  listGlobalBroadcasts,
  toggleGlobalBroadcast,
  deleteGlobalBroadcast,
  setUserRole,
  shouldRecordLoginHistory,
  upsertSession,
  verifyAdminPin,
  verifyAdminSessionToken,
  writeAudit,
};
